### ISSUE TITLE
Display document in markdown-mode

### ISSUE THREAD

**Issue by DogLooksGood** [astoff/code-cells.el#1]
Hi, this is an awesome package!

I wonder if it is possible to display markdown block in markdown format, (without the prefix `#`, or with markdown highlight). 

Thanks!

**Comment by astoff** [comment]
Is [this](https://github.com/astoff/code-cells.el#tweaking-the-ipynb-conversion) what you are asking about?

A fancier treatment of the markdown cells could be done, although I don't want to go as far as using [polymode](https://github.com/polymode/polymode) or something like that. In any case, it shouldn't be extremely hard to set it up yourself.

**Comment by DogLooksGood** [comment]
Thanks! this is what I'm looking for!
