### ISSUE TITLE
Code cell integrated into spacemacs

### ISSUE THREAD

**Issue by Rathur421** [astoff/code-cells.el#12]
Hi, I just wanted to let you know that code-cells have been integrated into the python layer of spacemacs.
 https://github.com/syl20bnr/spacemacs/pull/15425

Also thank you for this package it is really indispensable to my worflow and it seems like some other people will enjoy using it too on spacemacs!

You can close this issues

**Comment by astoff** [comment]
Nice, thanks for the heads up.
