### ISSUE TITLE
How to mark cell boundaries with horizontal divider in percent format

### ISSUE THREAD

**Issue by FlorianOtel** [astoff/code-cells.el#16]
Asking for guidance on how to mark cell boundary with horizontal divider -- as shown here: https://raw.githubusercontent.com/astoff/code-cells.el/images/screenshot.png 

After instructing `jupytext` to use [Jupytext - percent format]( https://github.com/mwouts/jupytext/blob/main/docs/formats.md#The-percent-format) the cells are shown correctly, but _without_ the horizontal divider as in the screenshot above. 

If this is a matter of configuring e.g. `outline-minor-mode` please provide instructions on how to do that and mark cell boundaries with horizontal divider. 

Kind TIA for the advice -- and thanks for creating this lovely piece of code  :)

**Comment by astoff** [comment]
You just need to enable `code-cells-mode`. If you don't see the highlight, there must be something else in your configuration conflicting with it (test with `emacs -Q`).

**Comment by FlorianOtel** [comment]
First, thanks for your answer

I have tried this: 
- starting emacs  `emacs -Q`
- loaded `.emacs.d/elpa/code-cells-0.3/code-cells-autoloads.el` 
- switched to `code-cells-mode`
- loaded ipynb file. 

Still no boundary between cells -- see attached screenshot (with light theme, it's the same with dark theme)

![image](https://user-images.githubusercontent.com/1360627/193425189-ef1af487-6a7d-4e89-8ea5-2fd5172b5e7e.png)

**Comment by astoff** [comment]
I seems, from the screenshot, that you are running Emacs on the terminal. There, "overlining" text is just not available.

There's not much I can do here, except, perhaps, add a different cell boundary face on the terminal. It might be tricky to find a safe face that will work on any theme, but I'm open to suggestions.
