### ISSUE TITLE
Jupytext option writes no code cells from Org-babel and Pandoc throws "Unkown writer"

### ISSUE THREAD

**Issue by progsi** [astoff/code-cells.el#17]
I can't really export org-mode to ipynb. 
Jupytext option writes no code cells from Org-babel and Pandoc throws "Unkown writer". Do you know why this could be the case?

**Comment by astoff** [comment]
This package has no relation to Org. What exactly are you attempting?

**Comment by progsi** [comment]
I was attempting to export an org-file with org-babel snippets to ipynb. This worked yesterday, but now not anymore (code cells are exported as markdown cells). Maybe I am confusing something with another ipynb package used.

**Comment by astoff** [comment]
Probably, yes. This package can load ipynb files as if they were a normal Python script, and save said scripts as ipynb. No interaction with Org is provided.
