### ISSUE TITLE
Emacs needs libjansson when running this

### ISSUE THREAD

**Issue by andreas-roehler** [astoff/code-cells.el#2]
Thanks for the excellent package.
Seems Emacs needs to be configured/compiled with libjansson library, which doesn't exit by default at my Debian/Ubuntu.
Got:
Debugger entered--Lisp error: (void-function json-parse-buffer)
 
Maybe mention something like
apt install libjansson-doc libjansson4 libjansson-dev (?)

**Comment by astoff** [comment]
Sure, I should add a check and warning message.

Now, just so I understand how common this is, did you encounter this issue with the Emacs distributed by Debian/Ubuntu, or is it one you built yourself? Are those `apt install` requirements for building or just running Emacs?

**Comment by andreas-roehler** [comment]
On 12.08.21 16:03, Augusto Stoffel wrote:
>
> Sure, I should add a check and warning message.
>
> Now, just so I understand how common this is, did you encounter this 
> issue with the Emacs distributed by Debian/Ubuntu, or is it one you 
> built yourself?
>
Got the error from a new built from current trunk of 2021.07.27

The Emacs shipped with my Debian 10 is a Emacs 26.1. As it's not even an 
Emacs27...

Usually use my own builds.

> Are those |apt install| requirements for building or just running Emacs?
>
libjansson seems only needed for the new json-stuff introduced in Emacs27.
