### ISSUE TITLE
jupyter-eval-region signature has changed

### ISSUE THREAD

**Issue by gmoutso** [astoff/code-cells.el#22]
This is a great package! Thanks.
`jupyter-eval-region` has changed signature and no longer is `(beg end)` but `(insert beg end)`. I have made the following changes to make code-cells work with [jupyter-emacs](https://github.com/nnicandro/emacs-jupyter) again

    (defun gm/jupyter-eval-region (beg end)
      (jupyter-eval-region nil beg end))
    (add-to-list 'code-cells-eval-region-commands '(jupyter-repl-interaction-mode . gm/jupyter-eval-region))

**Comment by gmoutso** [comment]
Changed function is [here](https://github.com/emacs-jupyter/jupyter/blob/1baabc8f2d0631f8f4308400f9a53f1aadd58d14/jupyter-client.el#L936)

**Comment by astoff** [comment]
This seems like a questionable API change. Do you know why they didn't make the new signature `(beg end &optional insert)`, an perhaps this could still be changed in jupyter-emacs?

**Comment by gmoutso** [comment]
Sorry no, I don't know. But I do use both packages a lot...

**Comment by LarryLegend33** [comment]
Hi I've encountered the same problem with code-cells-eval calls yielding a "Wrong number of arguments" error. Where exactly did you place this new function to get code-cells and jupyter-emacs to work together again? Thanks!

**Comment by chookity-pokk** [comment]
It would be nice if this could be mentioned in the README somewhere to make it easier for people to find.

**Comment by chookity-pokk** [comment]
> > Hi I've encountered the same problem with code-cells-eval calls yielding a "Wrong number of arguments" error. Where exactly did you place this new function to get code-cells and jupyter-emacs to work together again? Thanks!
> 
> Hi. All of the following can be placed in your init.el. First define a function like
> 
> ```
> (defun gm/jupyter-eval-region (beg end)
> (jupyter-eval-region nil beg end))
> ```
> 
> Then add this to `code-cells-eval-region-commands` either using the customize interface or add this again in your init.el: `(add-to-list 'code-cells-eval-region-commands '(jupyter-repl-interaction-mode . gm/jupyter-eval-region))`
> 
> Once you have done this, `eval-buffer` while in your init.el or restart emacs.

This doesn't work for me unless I first start a jupyter repl. Putting the function in my init works fine but it throws an error on the `(add-to-list 'code-cells-eval-region-commands '(jupyter-repl-interaction-mode . gm/jupyter-eval-region))` part with the backtrace below.

```
Debugger entered--Lisp error: (void-variable code-cells-eval-region-commands)
  (member '(jupyter-repl-interaction-mode . gm/jupyter-eval-region) code-cells-eval-region-commands)
  (if (member '(jupyter-repl-interaction-mode . gm/jupyter-eval-region) code-cells-eval-region-commands) code-cells-eval-region-commands (setq code-cells-eval-region-commands (cons '(jupyter-repl-interaction-mode . gm/jupyter-eval-region) code-cells-eval-region-commands)))
  eval-buffer(#<buffer  *load*-206962> nil "/Users/hankgreenburg/.emacs.d/init.el" nil t)  ; Reading at buffer position 52141
  load-with-code-conversion("/Users/hankgreenburg/.emacs.d/init.el" "/Users/hankgreenburg/.emacs.d/init.el" nil nil)
  load("/Users/hankgreenburg/.emacs.d/init.el" nil nil t)
  load-file("/Users/hankgreenburg/.emacs.d/init.el")
  org-babel-load-file("/Users/hankgreenburg/.emacs.d/init.org")
  eval-buffer(#<buffer  *load*> nil "/Users/hankgreenburg/.emacs" nil t)  ; Reading at buffer position 410
  load-with-code-conversion("/Users/hankgreenburg/.emacs" "/Users/hankgreenburg/.emacs" t t)
  load("~/.emacs" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x1552091b4c8cfd>) #f(compiled-function () #<bytecode -0x1f3c61addc0da035>) t)
  command-line()
  normal-top-level()
```

**Comment by astoff** [comment]
Since https://github.com/emacs-jupyter/jupyter/issues/490 was ignored, I reluctantly decided to add a workaround to code-cells. Let me know in case you still have trouble.
