### ISSUE TITLE
[Feature Request] Display something in the modeline when code is running

### ISSUE THREAD

**Issue by chookity-pokk** [astoff/code-cells.el#23]
I am using this with `jupyter` and have a few cells that take a bit of time to run and that sometimes leads me to wonder if the code is actually running. So it would be nice if there was something on the modeline with a ✔️ for code being finished and a timer or 🕐 icon for code that is still running.

**Comment by astoff** [comment]
This feature should be provided by the jupyter packge. In fact, I'm checking `jupyter-repl-interaction-mode-line` and it seem to do exactly that?

From this package's point of view, it would be very hard, probably impossible, to provide such an indication in a way that work with every possible REPL, or even with all Comint-based ones.
