### ISSUE TITLE
notebook is not getting converted when written to file

### ISSUE THREAD

**Issue by vanangamudi** [astoff/code-cells.el#25]
Emacs version:
GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.16.0)

Configuration:
```
#+begin_src sh
  pip install jupyterlab jupytext
#+end_src
```
```
#+begin_src emacs-lisp
  (use-package code-cells
    :config
    (setq code-cells-convert-ipynb-style '(("pandoc" "--to" "ipynb" "--from" "org")
                                           ("pandoc" "--to" "org" "--from" "ipynb")
                                           (lambda () #'org-mode))))
#+end_src
```

The notebook file sample.ipynb gets converted automatically into org-mode, but when writing to the file it stays in org-mode format.

**Comment by astoff** [comment]
It works for me, so I will close to issue. Feel free to reopen the discussion.
