### ISSUE TITLE
JSON readtable error

### ISSUE THREAD

**Issue by guibor** [astoff/code-cells.el#29]
I get the following error:

"json-read: JSON readtable error:"

whenever I run `code-cells-convert-ipynb()`

backtrace

```
Debugger entered--Lisp error: (json-readtable-error 35)
  signal(json-readtable-error (35))
  json-read()
  code-cells--guess-mode()
  code-cells-convert-ipynb()
 ```

**Comment by astoff** [comment]
I can't reproduce, but this should be fixed in 498edb3.
