### ISSUE TITLE
see executed command in python buffer

### ISSUE THREAD

**Issue by mazer-ai** [astoff/code-cells.el#3]
Just found this yesterday and already finding it really useful.  One quick question/feature-request: any ideas on how to get `comint` to copy the executed string into the output buffer when you run `code-cells-eval` into the REPL buffer? It would be really useful to be able to have the command visible above the output, instead of just displayed transiently in the command area.

I feel like I'm missing something obvious here, but after an afternoon pouring through comint.el, python.el and code-cells.el and googling, I just can't figure out how the right way to do it.

Seems like it would be incredibly useful to facilitate using this as a substitute for a full-blown jupyter notebook instance. FWIW -- python-cell.el is in the same boat.

**Comment by astoff** [comment]
This seems to be something a bit tricky to implement, and probably has to be done separately for each comint. Of course, if someone figures out how to do it in a reasonably clean way, then I'd be happy to merge it.

The [emacs-jupyter](https://github.com/nnicandro/emacs-jupyter) package provides an option to enable exactly the behavior you descried. It's called `jupyter-repl-echo-eval-p`. I must say that I used it for a while, and then realized it's not as useful as I had anticipated.

Also, in case you are already using (the unrelased) Emacs 28, there are some improvements in the Python shell. For instance, if you evaluate a compound statement with `code-cells-eval` or `python-shell-send-region`, then the value returned by the last expression is printed, just like Jupyter does.

**Comment by mazer-ai** [comment]
Well, at least glad to know it's not just me or something bizzare about my
setup!

I just hacked up a version of `python-shell-send-region` that sends a print
command with the region before actually sending the region to eval. And
then set `code-cells-eval-region-command` to point there. Very fragile, but
enough to help me see how useful this will be before spending real time
trying to figure out a proper solution.

Right now, I can't run `emacs-jupyter` without compiling custom emacs --
available emacs for ubunut/mint are not compilled with module support...
this is known issue according to the emacs-jupyter issue tracker.

Thanks!

**Comment by astoff** [comment]
All right, I opened a Wiki, which should be open for all to edit (let me know otherwise). Thanks!
