### ISSUE TITLE
Support for `python-ts-mode`?

### ISSUE THREAD

**Issue by swflint** [astoff/code-cells.el#32]
`python-ts-mode` is not directly supported, but it looks like adding `(python-ts-mode . python-shell-send-region)` to `code-cells-eval-region-commands` may work.

**Comment by astoff** [comment]
Interesting, in Emacs 30 I get `(provided-mode-derived-p 'python-ts-mode 'python-mode) ;=> t` so it should work without changes. But indeed this is not the case in Emacs ≤ 29.

**Comment by swflint** [comment]
Weirdly, that makes sense.  Thank you!
