### ISSUE TITLE
Question/Curiosity

### ISSUE THREAD

**Issue by ChauhanT** [astoff/code-cells.el#34]
Hi, 

I am working on a project stored at a path P. I have a notebook (say, P/Q/N.ipynb) with a function that accepts paths relative to the file and acts on them. With code-cells, when I pass that particular statement to the inferior shell (I use `emacs-direnv), it assumes the cwd (e.g., Path.cwd) to be the project root P and not the directory where the notebook is (i.e., P/Q). 

I was wondering if this is a known problem and whether there is an easy fix to this. I do not want to hard-code the paths because it makes sharing the notebooks more difficult. 

Cheers!

Happy to take this down, but I didn't know where else to reach out for help. Google is dead, and forums are slowly dying.

**Comment by astoff** [comment]
This is not related to code-cells per se, but to the inferior shell. IMO it makes sense to start the inferior process in the project root and not in the current buffer's directory, but this means all relative paths must be written relative to the project root.

Unfortunately Jupyter does it the other way around and runs the "kernel" in the notebooks directory, so you must be aware of that if you share your notebook with other people.

**Comment by ChauhanT** [comment]
Ah gotcha. I did not know about this jupyter idiosyncrasy. Thanks !!
