### ISSUE TITLE
Document the `# *` syntax

### ISSUE THREAD

**Issue by memeplex** [astoff/code-cells.el#4]
The syntax

```
#* Optional title
#** Optional title
...
```

has the problem that it's not PEP8 compatible (missing a space after #), so linters can get very annoying with it.

It seems that you also support:

```
# * Optional title
# ** Optional title
...
```

but it's not documented.

**Comment by astoff** [comment]
Okay, but I just added a subtle suggestion that this is valid in the readme.

**Comment by astoff** [comment]
I'm getting lots of false positives where people use the asterisk as bullet point and those are considered cell boundaries. So I'm considering changing things so that no space is allowed between the comment syntax and the asterisk. Do you have a strong objection?
