### ISSUE TITLE
Suggestions on working with linters?

### ISSUE THREAD

**Issue by Yevgnen** [astoff/code-cells.el#7]
Thanks for the package. I've switched from `jupyter` in `Org` mode to `code-cells` for data analysis. The only issue is, the linters (`pylint`, `mypy`, etc. ) do not work with the raw `.ipynb` files, and of course they should not. The error messages always show strange messages and wrong position information like

<img width="965" alt="Screen Shot 2021-11-01 at 10 59 43 AM" src="https://user-images.githubusercontent.com/16749790/139615767-e18927ac-169c-4145-94bf-725639f54e57.png">
<img width="977" alt="Screen Shot 2021-11-01 at 11 00 30 AM" src="https://user-images.githubusercontent.com/16749790/139615833-0f09e1b5-7106-4dfa-b2db-583b08169b1f.png">

Can this be fixed or do you have any suggestion on this? Thanks.

**Comment by astoff** [comment]
Yes, this is annoying. Same problem if you try to grep a collection of notebooks.

If I run the linters through a language server, then it works. Otherwise, you can save and edit the .py version of these notebooks. I guess I have no better suggestion here.

**Comment by Yevgnen** [comment]
I haven't run linters through language servers before, thanks for your advices!
