### ISSUE TITLE
Supports for `light` format?

### ISSUE THREAD

**Issue by Yevgnen** [astoff/code-cells.el#8]
The [doc](https://github.com/astoff/code-cells.el/blob/master/code-cells.el#L69) of `code-cells-boundary-markers` says 

> They should match immediately after a comment start at the
beginning of a line. 

It seems that [light format](https://github.com/mwouts/jupytext/blob/main/docs/formats.md#the-light-format) is not supported currently. Is something like `^$` for `page-delimiter` sufficient to add this support?

**Comment by astoff** [comment]
Well, I guess one could implement this, but it would be a bit complicated. Just look at the examples in the documentation you linked and you'll see most empty lines are not cell breaks.

Why would prefer the light format? I see no advantage in it.

**Comment by Yevgnen** [comment]
I personally prefer no markers and would like to make the text cells look like natural comment in common Python scripts. I'm not a big fan of `jupyter` so I generally write scripts, spilt and, wrap them in a notebook, because in some cases I have to keep notebooks to work with others...

**Comment by jdtsmith** [comment]
Is the "percent" format mentioned there the official format for code-cells?

**Comment by astoff** [comment]
@jdtsmith I believe this is sufficiently specified in the block right below the screenshot in the README?

**Comment by astoff** [comment]
I think there's no practical way to support the light format, so I'll close the issue.
